source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AutoLinearLayoutView_Example', :exclusive => true do
  pod 'AutoLinearLayoutView', :path => '../'
end

target 'AutoLinearLayoutView_Tests', :exclusive => true do
  pod 'AutoLinearLayoutView', :path => '../'

  
end
