source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AutoLinearLayoutView_Example' do
  pod 'AutoLinearLayoutView', :path => '../'
end

target 'AutoLinearLayoutView_Tests' do
  pod 'AutoLinearLayoutView', :path => '../'

  
end
